/* =========================================================
   CoreStorm Global — scripts/fetch-assets.js
   Localises every remote asset so the site is fully
   self-hosted: no Unsplash hot-linking, no Google Fonts
   requests at runtime. Run once (or whenever imagery
   changes), commit the results in assets/.

     node scripts/fetch-assets.js

   Downloads:
     assets/img/*.jpg          — stock photos, resized per use
     assets/fonts/*.woff2      — Playfair Display 600 (+italic),
                                 Inter 400/500/600 (latin subset)
     assets/fonts/fonts.css    — generated @font-face rules

   Requires Node 18+ (global fetch) and "sharp".
   ========================================================= */

"use strict";

const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const ROOT = path.join(__dirname, "..");
const IMG_DIR = path.join(ROOT, "assets", "img");
const FONT_DIR = path.join(ROOT, "assets", "fonts");

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/124.0 Safari/537.36";

/* Each entry: unsplash photo id, output name, width, jpeg quality.
   Subjects verified by eye — every file depicts real solar hardware. */
const IMAGES = [
  // hero
  { id: "1509391366360-2e959784a276", out: "hero-array.jpg",         w: 1800, q: 74 },
  // products — solar panels
  { id: "1592833159155-c62df1b65634", out: "panels-ground.jpg",      w: 1100, q: 74 },
  { id: "1613665813446-82a78c468a1d", out: "rooftop-install-sm.jpg", w: 500,  q: 74 },
  { id: "1545209463-e2825498edbf",    out: "field-array-sm.jpg",     w: 500,  q: 74 },
  // products — inverters
  { id: "1624397640148-949b1732bb0a", out: "installer-panel.jpg",    w: 1100, q: 74 },
  { id: "1559302504-64aae6ca6b6d",    out: "tech-wiring-sm.jpg",     w: 500,  q: 74 },
  { id: "1497440001374-f26997328c1b", out: "grid-array-sm.jpg",      w: 500,  q: 74 },
  // products — battery / off-grid
  { id: "1508514177221-188b1cf16e9d", out: "offgrid-array.jpg",      w: 1100, q: 74 },
  { id: "1595437193398-f24279553f4f", out: "solar-wind-sm.jpg",      w: 500,  q: 74 },
  { id: "1509391366360-2e959784a276", out: "hero-array-sm.jpg",      w: 500,  q: 74 },
  // projects
  { id: "1592833159155-c62df1b65634", out: "panels-ground-md.jpg",   w: 760,  q: 74 },
  { id: "1611365892117-00ac5ef43c90", out: "golden-array-md.jpg",    w: 760,  q: 74 },
  { id: "1613665813446-82a78c468a1d", out: "rooftop-install-md.jpg", w: 760,  q: 74 },
  // about
  { id: "1611365892117-00ac5ef43c90", out: "golden-array.jpg",       w: 1000, q: 74 },
];

/* Google Fonts css2 specs to localise (latin subset only). */
const FONTS = [
  {
    family: "Playfair Display",
    css2: "family=Playfair+Display:ital,wght@0,600;1,600",
  },
  {
    family: "Inter",
    css2: "family=Inter:wght@400;500;600",
  },
];

const log = (...a) => console.log(...a);

async function fetchBuffer(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

async function fetchImages() {
  log(`\n🖼  Downloading ${IMAGES.length} image variants…`);
  // Cache originals per photo id so each id downloads once.
  const originals = new Map();
  for (const { id, out, w, q } of IMAGES) {
    if (!originals.has(id)) {
      const url = `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1900&q=85`;
      originals.set(id, await fetchBuffer(url));
    }
    const buf = await sharp(originals.get(id))
      .resize({ width: w, withoutEnlargement: true })
      .jpeg({ quality: q, mozjpeg: true })
      .toBuffer();
    fs.writeFileSync(path.join(IMG_DIR, out), buf);
    log(`   ✓ ${out.padEnd(24)} ${w}w  ${(buf.length / 1024) | 0}KB`);
  }
}

async function fetchFonts() {
  log(`\n🔤 Downloading fonts (latin subset)…`);
  let cssOut =
    "/* Generated by scripts/fetch-assets.js — self-hosted fonts */\n";

  for (const font of FONTS) {
    const url = `https://fonts.googleapis.com/css2?${font.css2}&display=swap`;
    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
    const css = await res.text();

    // Keep only the /* latin */ blocks.
    const blocks = css.split("/*").map((b) => "/*" + b);
    const latin = blocks.filter((b) => b.trim().startsWith("/* latin */"));

    for (let block of latin) {
      const m = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      if (!m) continue;
      const remote = m[1];
      const style = /font-style:\s*italic/.test(block) ? "italic" : "normal";
      const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || "400";
      const fname = `${font.family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${style}.woff2`;

      const buf = await fetchBuffer(remote);
      fs.writeFileSync(path.join(FONT_DIR, fname), buf);
      log(`   ✓ ${fname.padEnd(36)} ${(buf.length / 1024) | 0}KB`);

      block = block.replace(remote, fname); // relative to fonts.css
      cssOut += block.trim() + "\n";
    }
  }
  fs.writeFileSync(path.join(FONT_DIR, "fonts.css"), cssOut);
  log(`   ✓ fonts.css written`);
}

(async () => {
  try {
    fs.mkdirSync(IMG_DIR, { recursive: true });
    fs.mkdirSync(FONT_DIR, { recursive: true });
    await fetchImages();
    await fetchFonts();
    log(`\n✅ All assets localised under assets/ — the site now runs with zero external requests.`);
  } catch (err) {
    console.error("\n💥 fetch-assets failed:", err.message);
    process.exit(1);
  }
})();
